input_data:
  file1 : "../data/raw/movies.csv"


output_data:
  file1 : "../data/clean/df_movies_clean_fixed_francisca.csv"
  file2 : "../data/clean/df_movies_clean_francisca.csv"
  file3 : "../data/clean/goncalo_clean.csv"
  file4 : "../data/clean/goncalo_features.csv"
  file5 : "../data/clean/H2_X_test_scaled.csv"
  file6 : "../data/clean/H2_X_test.csv"
  file7 : "../data/clean/H2_X_train_scaled.csv"
  file8 : "../data/clean/H2_X_train.csv"
  file9 : "../data/clean/H2_y_test.csv"
  file10: "../data/clean/H2_y_train.csv"